# Generated by Django 2.0 on 2020-03-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naiades_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=512)),
                ('filename', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='updatefile',
            unique_together={('path', 'filename')},
        ),
    ]
