# Generated by Django 2.0 on 2020-03-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naiades_dashboard', '0004_meterinfoaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterinfo',
            name='user',
        ),
    ]
