# Generated by Django 2.0 on 2020-12-30 13:15
import os
import csv

from decimal import Decimal

from django.db import migrations, models

from project.settings import BASE_DIR


def load_meter_info_data(apps, schema_editor):
    # get models at this stage
    MeterInfo = apps.get_model("naiades_dashboard", "MeterInfo")

    # read data
    with open(
            os.path.join(BASE_DIR, 'naiades_dashboard/data/locations-20201229.csv'),
            'r', encoding='utf-8'
    ) as f:
        data = list(csv.DictReader(f))

    # create or update meter infos
    for row in data:
        # get or create in memory
        meter_info = MeterInfo.objects.filter(meter_number=row["meter_id"]).first() or \
                     MeterInfo(meter_number=row["meter_id"])

        # update location info
        meter_info.latitude = Decimal(row["lat"])
        meter_info.longitude = Decimal(row["lng"])
        meter_info.address = row["address"]

        # update service info
        meter_info.service_point_id = int(row["service_point_id"])
        meter_info.service_connection_id = int(row["service_connection_id"])

        # save
        meter_info.save()


class Migration(migrations.Migration):

    dependencies = [
        ('naiades_dashboard', '0007_consumption_is_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterinfo',
            name='address',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='meterinfo',
            name='service_connection_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meterinfo',
            name='service_point_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(load_meter_info_data, reverse_code=lambda _, __: None),
    ]
