# Generated by Django 2.0 on 2020-12-30 13:15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naiades_dashboard', '0007_consumption_is_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterinfo',
            name='address',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='meterinfo',
            name='service_connection_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meterinfo',
            name='service_point_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
