# Generated by Django 2.0 on 2021-12-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naiades_dashboard', '0008_auto_20201230_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterinfo',
            name='size',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
