# Generated by Django 2.0 on 2022-03-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naiades_dashboard', '0010_recreate_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumption',
            old_name='is_school',
            new_name='in_dashboard',
        ),
        migrations.AddField(
            model_name='meterinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meterinfo',
            name='in_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meterinfo',
            name='in_dashboard_changed',
            field=models.BooleanField(default=False),
        ),
    ]
