# Generated by Django 2.0 on 2022-08-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naiades_dashboard', '0012_consumption_dashboard_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionByActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(decimal_places=16, max_digits=32)),
                ('date', models.DateTimeField(db_index=True)),
                ('year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('week', models.SmallIntegerField()),
                ('day', models.SmallIntegerField()),
                ('hour', models.SmallIntegerField()),
                ('estimated', models.BooleanField(default=False)),
                ('activity', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Consumption by Activity',
                'verbose_name_plural': 'Consumptions by Activity',
            },
        ),
        migrations.AlterField(
            model_name='consumption',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='consumptionbyactivity',
            unique_together={('date', 'hour', 'activity', 'estimated')},
        ),
    ]
