# Generated by Django 2.0 on 2020-03-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
